import React, { useState } from "react";
import Head from "next/head";
import { Col, Container, Row, Button, Modal, Form } from "react-bootstrap";
import { Gap, Header, Title } from "@/components";
import { registerUser } from "@/hooks/useUser";
import Swal from "sweetalert2";
import { useRouter } from "next/router";

function Register() {
  const router = useRouter();

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleRegister = (event) => {
    event.preventDefault();
    registerUser({ name, email, password });
    Swal.fire({
      icon: "success",
      title: "Register Successful",
      showConfirmButton: false,
      timer: 1500,
    });
    router.push("/login");
  };
  return (
    <>
      <Head>
        <title>Register</title>
        <meta
          name="description"
          content="Register Page - Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <Gap />
        <Title title="Register User" />
        <Gap />
        <Row className="justify-content-md-center">
          <Col md={5}>
            <Form onSubmit={handleRegister}>
              <Form.Group className="mb-3">
                <Form.Label>Name</Form.Label>
                <Form.Control
                  type="text"
                  name="name"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  required
                />
              </Form.Group>
              <Form.Group className="mb-3">
                <Form.Label>Email</Form.Label>
                <Form.Control
                  type="email"
                  name="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </Form.Group>
              <Form.Group className="mb-3">
                <Form.Label>Password</Form.Label>
                <Form.Control
                  type="password"
                  name="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </Form.Group>
              <Button type="submit" variant="success">
                Register
              </Button>
            </Form>
          </Col>
        </Row>
      </Container>
    </>
  );
}

export default Register;
