import React, { useState, useEffect } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import { useRouter } from "next/router";
import { Col, Container, Row } from "react-bootstrap";
import { Gap, Header, OrderForm, ShoppingCart, Title } from "@/components";
import { getCarts, getTotalPrice } from "@/hooks/useCart";
import { useQuery } from "@tanstack/react-query";
import Swal from "sweetalert2";

function Cart() {
  const router = useRouter();
  const [user, setUser] = useState("");

  useEffect(() => {
    const token = localStorage.getItem("token");
    const userId = localStorage.getItem("userId");
    if (token) {
      setUser(userId);
    } else {
      Swal.fire({
        icon: "warning",
        title: "Login first before viewing shopping cart",
        showConfirmButton: false,
        timer: 2000,
      });
      router.push("/");
    }
  }, []);

  const { data: carts } = useQuery({
    queryKey: ["carts", { user }],
    queryFn: async () => await getCarts(user),
  });

  const { data: totalPrice } = useQuery({
    queryKey: ["totalPrice", { user }],
    queryFn: async () => await getTotalPrice(user),
  });

  return (
    <>
      <Head>
        <title>Shopping Cart</title>
        <meta
          name="description"
          content="Shopping Cart - Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <Gap />
        <Title title="Shopping Cart" />
        <Gap />
        <Row>
          <Col md={7}>
            <ShoppingCart user={user} carts={carts} totalPrice={totalPrice} />
          </Col>
          <Col md={5}>
            <OrderForm user={user} carts={carts} totalPrice={totalPrice} />
          </Col>
        </Row>
        <Gap />
      </Container>
    </>
  );
}

// export default Cart;
export default dynamic (() => Promise.resolve(Cart), {ssr: false})

