import React, { useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import { useRouter } from "next/router";
import { Container, Row, Col, Table } from "react-bootstrap";
import { Gap, Header, Title } from "@/components";
import { numberWithCommas } from "@/utils/utils";
import { useQuery } from "@tanstack/react-query";
import { getOrderById } from "@/hooks/useOrder";

const OrderDetails = () => {
  const router = useRouter();
  const { id } = router.query;

  const { data: orderDetails } = useQuery({
    queryKey: ["orderDetails", { id }],
    queryFn: async () => await getOrderById(id),
  });

  return (
    <div>
      <Head>
        <title>Order Details</title>
        <meta
          name="description"
          content="Order Details - Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <Gap />
        <Title title="Order Details" />
        <Gap />
        <Row className="justify-content-md-center">
          <Col md={5}>
            <Table bordered striped>
              <tbody>
                <tr>
                  <td>Order ID</td>
                  <td>{orderDetails?._id}</td>
                </tr>
                <tr>
                  <td>Order Date</td>
                  <td>{orderDetails?.createdAt}</td>
                </tr>
                <tr>
                  <td>Status</td>
                  <td>{orderDetails?.status}</td>
                </tr>
              </tbody>
            </Table>
          </Col>
          <Col md={5}>
            <Table bordered striped>
              <tbody>
                <tr>
                  <td>Recipient's Name</td>
                  <td>{orderDetails?.recipient}</td>
                </tr>
                <tr>
                  <td>Delivery Address</td>
                  <td>{orderDetails?.deliveryAddress}</td>
                </tr>
                <tr>
                  <td>Note</td>
                  <td>{orderDetails?.note}</td>
                </tr>
              </tbody>
            </Table>
          </Col>
        </Row>
        <Row className="justify-content-md-center">
          <Col md={8}>
          <Table bordered striped>
            <thead>
              <tr>
                <td>
                  <p style={{ textAlign: "center" }}>No</p>
                </td>
                <td>
                  <p style={{ textAlign: "center" }}>Product Item</p>
                </td>
                <td>
                  <p style={{ textAlign: "center" }}>Quantity</p>
                </td>
                <td>
                  <p style={{ textAlign: "center" }}>Subtotal</p>
                </td>
              </tr>
            </thead>
            <tbody>
              {orderDetails?.orderItem?.map((item, index) => (
                <>
                  <tr key={item._id}>
                    <td style={{ verticalAlign: "middle" }}>
                      <p style={{ textAlign: "center" }}>{index + 1}</p>
                    </td>
                    <td style={{ verticalAlign: "middle" }}>
                      <p style={{ textAlign: "center" }}>{item?.product}</p>
                      <p style={{ textAlign: "center" }}>
                        Rp {numberWithCommas(item?.price)}
                      </p>
                    </td>
                    <td style={{ verticalAlign: "middle" }}>
                      <p style={{ textAlign: "center" }}>{item?.quantity}</p>
                    </td>
                    <td style={{ verticalAlign: "middle" }}>
                      <p style={{ textAlign: "center" }}>
                        Rp {numberWithCommas(item?.subtotal)}
                      </p>
                    </td>
                  </tr>
                </>
              ))}

              <tr>
                <td colSpan={3}>
                  <p style={{ textAlign: "center" }}>Total</p>
                </td>
                <td>
                  <p style={{ textAlign: "center" }}>
                    Rp {numberWithCommas(parseInt(orderDetails?.totalPrice))}
                  </p>
                </td>
              </tr>
            </tbody>
          </Table>
          </Col>
        </Row>
      </Container>
    </div>
  );
};

// export default OrderDetails;
export default dynamic(() => Promise.resolve(OrderDetails), { ssr: false });
