import React, { useState } from "react";
import Head from "next/head";
import { Col, Container, Row } from "react-bootstrap";
import { Category, Content, Gap, Header, Title } from "@/components";
import { useQuery } from "@tanstack/react-query";
import { getProducts } from "@/hooks/useProduct";

export default function Home() {
  const [categoryId, setCategoryId] = useState("all");

  const { data: products } = useQuery({
    queryKey: ["products", { categoryId }],
    queryFn: async () => await getProducts(categoryId),
  });

  const handleCategory = async (categoryId) => {
    setCategoryId(categoryId);
  };

  return (
    <>
      <Head>
        <title>Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <Gap />
        <Title title="List of Products" />
        <Gap />
        <Row>
          <Col md={3}>
            <Category handleCategory={handleCategory} />
          </Col>
          <Col md={9}>
            <Content products={products} />
          </Col>
        </Row>
        <Gap />
      </Container>
    </>
  );
}
